[package]
name = "grabbit"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.4"
hashbrown = { version = "0.7.0", features = ["serde"] }
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.104", features = ["derive"] }
structopt = "0.3.11"

[dev-dependencies]
serde_json = "1.0.48"
